package:
  name: bmake
  version: "20240414"
  epoch: 0
  description: Portable version of the NetBSD make build tool
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - tzdata

pipeline:
  - uses: fetch
    with:
      expected-sha256: e1ba6c230cb3acf8b4c0885efaf3ffba3905942784b29d0f7fe22201542a5d56
      uri: http://www.crufty.net/ftp/pub/sjg/bmake-${{package.version}}.tar.gz
      strip-components: 0

  - runs: |
      ./bmake/boot-strap \
        --prefix=/usr \
        --install-destdir=${{targets.destdir}} \
        --install

subpackages:
  - name: bmake-doc
    pipeline:
      - uses: split/manpages
    description: bmake manpages

update:
  enabled: true
  release-monitor:
    identifier: 208
