package:
  name: cilium-cli
  version: 0.16.3
  epoch: 1
  description: CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium-cli
      tag: v${{package.version}}
      expected-commit: de740a64da1b12dc8488cf3af2474c60d52c349e
      destination: cilium-cli

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v25.0.5
      modroot: cilium-cli

  - runs: |
      cd cilium-cli
      make install
      install -Dm755  /usr/local/bin/cilium ${{targets.destdir}}/usr/bin/cilium

  - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/cilium-cli
    strip-prefix: v
