package:
  name: clusterctl
  version: 1.7.1
  epoch: 0
  description: A command line tool to manage clusters created by cluster API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}
      expected-commit: ef04465b2ba76214eea570e27e8146c96412e32a

  - uses: go/build
    with:
      packages: ./cmd/clusterctl
      repository: https://github.com/kubernetes-sigs/cluster-api
      ldflags: $(hack/version.sh)
      output: clusterctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
