package:
  name: composer
  version: 2.7.3
  epoch: 0
  description: "the PHP package manager"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - git
      - php

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://getcomposer.org/download/${{package.version}}/composer.phar
      expected-sha256: fcc02ff044b5a04fbecff0158cb6041c25e8f78ac494098736fecd2bb4f381e4
      extract: "false"
      delete: "false"

  - name: Install Composer
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      mkdir -p "${EXEC_DIR}"
      mv composer.phar "${EXEC_DIR}/composer"
      chmod +x "${EXEC_DIR}/composer"

update:
  enabled: true
  github:
    identifier: composer/composer
