package:
  name: controller-gen
  version: 0.15.0
  epoch: 0
  description: Tools to use with the controller-runtime libraries
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: go/install
    with:
      package: sigs.k8s.io/controller-tools/cmd/controller-gen
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/controller-tools
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - runs: |
        controller-gen --version
