package:
  name: corepack
  version: 0.28.0
  epoch: 0
  description: Zero-runtime-dependency package acting as bridge between Node projects and their package managers
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5bf3db93097b7e851e2f371c8f4c713db8036a8d3664ed250cdf072e4d4114fc
      uri: https://github.com/nodejs/corepack/releases/download/v${{package.version}}/corepack.tgz
      strip-components: 0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/node_modules/corepack
      cp -R package/* ${{targets.destdir}}/usr/share/node_modules/corepack/

      # Remove windows specific files.
      rm ${{targets.destdir}}/usr/share/node_modules/corepack/shims/*.cmd
      rm ${{targets.destdir}}/usr/share/node_modules/corepack/shims/*.ps1
      rm -rf ${{targets.destdir}}/usr/share/node_modules/corepack/shims/nodewin

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /usr/share/node_modules/corepack/dist/corepack.js ${{targets.destdir}}/usr/bin/corepack

  - uses: strip

update:
  enabled: true
  github:
    identifier: nodejs/corepack
    strip-prefix: v
