package:
  name: cosign
  version: 2.2.4
  epoch: 1
  description: Container Signing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2e31e8638de1869514cb0478796d2b55b455552fbd03c3b7ba0edf27b0b5b944
      uri: https://github.com/sigstore/cosign/archive/v${{package.version}}/cosign-v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9 k8s.io/apimachinery@v1.16.13 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      ldflags: -s -w -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
      output: cosign
      packages: ./cmd/cosign

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/cosign
    strip-prefix: v
