package:
  name: curl-rustls
  version: 8.7.1
  epoch: 0
  description: "URL retrieval utility and library"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - libcurl-rustls4
  checks:
    disabled:
      - empty # curl-rustls is expected to be empty, it brings in a runtime dep on libcurl-rustls4

environment:
  contents:
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpsl-dev
      - libtool
      - nghttp2-dev
      - openssl-dev
      - perl
      - rustls-ffi-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://curl.se/download/curl-${{package.version}}.tar.xz
      expected-sha256: 6fea2aac6a4610fbd0400afb0bcddbe7258a64c63f1f68e5855ebc0c659710cd

  - uses: patch
    with:
      patches: 9c4209837094781d5eef69ae6bcad0e86b64bf99.patch 5a50cb5a18a141a463148562dab83fa3be1a3b90.patch

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: |
        --enable-ipv6 \
        --enable-unix-sockets \
        --without-openssl \
        --with-rustls \
        --with-nghttp2 \
        --with-pic \
        --disable-ldap \
        --without-libssh2

  - uses: autoconf/make

  - runs: |
      make install DESTDIR="/home/build/curl-rustls"

subpackages:
  - name: "libcurl-rustls4"
    description: "curl library (rustls backend)"
    dependencies:
      provider-priority: 10
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "/home/build/curl-rustls"/usr/lib/libcurl.so.* "${{targets.subpkgdir}}"/usr/lib/
          strip "${{targets.subpkgdir}}"/usr/lib/libcurl.so.*

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/curl
    strip-prefix: curl-
