package:
  name: dagger
  version: 0.10.2
  epoch: 1
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: f123072dfde8fd15f9c9ecf5bc2c11c5228ac5e7

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      ldflags: -s -w  -X github.com/dagger/dagger/engine.Version=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
