package:
  name: dagger
  version: 0.11.1
  epoch: 0
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: 53eb40c8f50e941dda915e14ee37d06cd4f48ef2

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.0.0

  - uses: go/build
    with:
      ldflags: -s -w  -X github.com/dagger/dagger/engine.Version=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
