package:
  name: eslint
  version: 9.1.1
  epoch: 0
  description: An AST-based pattern checker for JavaScript
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eslint/eslint
      tag: v${{package.version}}
      expected-commit: b4d2512809a1b28466ad1ce5af9d01c181b9bf9e

  - runs: |
      npm install --omit=dev
      npm prune --production
      _npmdir=/usr/lib/node_modules/${{package.name}}
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/$_npmdir
      install -Dm755 bin/${{package.name}}.js "${{targets.destdir}}"/usr/bin/${{package.name}}

      rsync -r --exclude .cache --exclude .package-lock.json conf lib messages \
          node_modules package.json "${{targets.destdir}}"/$_npmdir

  - uses: strip

update:
  enabled: true
  github:
    identifier: eslint/eslint
    use-tag: true
    tag-filter: v
    strip-prefix: v
