package:
  name: external-secrets-operator
  version: 0.9.16
  epoch: 0
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - yq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: 3d96be0d53817cde9e1c431b4b51550614e064df

  - runs: |
      make build-$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D bin/external-secrets-$(go env GOOS)-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/external-secrets

  - uses: strip

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
