package:
  name: external-secrets-operator
  version: 0.9.13
  epoch: 4
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - yq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: 79b42bde4b82667eddcc5a52685754a97a126a03

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 github.com/lestrrat-go/jwx/v2@v2.0.21 google.golang.org/protobuf@v1.33.0

  - runs: |
      make build-$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D bin/external-secrets-$(go env GOOS)-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/external-secrets

  - uses: strip

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
