package:
  name: flannel
  version: 0.25.1
  epoch: 1
  description: flannel is a network fabric for containers, designed for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flannel-io/flannel
      tag: v${{package.version}}
      expected-commit: f0215be22814581788ac48047b926dd011bc861d

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0

  # Build with CGO_ENABLED=1 to include the UDP backend
  - runs: |
      CGO_ENABLED=0
      if [ "$(go env GOARCH)" = "amd64" ]; then
        CGO_ENABLED=1
      fi
      CGO_ENABLED=$(CGO_ENABLED) go build -o "${{targets.destdir}}"/usr/bin/flanneld \
        -ldflags '-s -w -extldflags "-static" -X github.com/flannel-io/flannel/pkg/version.version=${{package.version}}'

  - uses: strip

update:
  enabled: true
  github:
    identifier: flannel-io/flannel
    strip-prefix: v
