package:
  name: flannel-cni-plugin
  version: 1.4.1
  epoch: 0
  description: flannel cni plugin
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flannel-io/cni-plugin
      tag: v${{package.version}}-flannel1
      expected-commit: 85206d1cdc253d9a3720e2248b4959fb5acce6d2

  - runs: |
      # Ensure we build statically since CNI plugins often get moved onto the
      # host machine where we can't guarantee GLIBC verion compatibility
      # `-extldflags "-static"` is included by default
      CGO_ENABLED=0 \
      EXTRA_LDFLAGS="-s -w" \
      scripts/build_flannel.sh

      install -Dm755 dist/flannel-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/flannel

  - uses: strip

subpackages:
  - name: flannel-cni-plugin-compat
    dependencies:
      runtime:
        - flannel-cni-plugin
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opt/cni/bin
          ln -s /usr/bin/flannel "${{targets.subpkgdir}}"/opt/cni/bin/flannel

update:
  enabled: true
  github:
    identifier: flannel-io/cni-plugin
    strip-prefix: v
    strip-suffix: -flannel1
