package:
  name: fping
  version: "5.2"
  epoch: 0
  description: A utility to ping multiple hosts at once
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-utils

pipeline:
  - uses: fetch
    with:
      expected-sha256: a7692d10d73fb0bb76e1f7459aa7f19bbcdbfc5adbedef02f468974b18b0e42f
      uri: https://fping.org/dist/fping-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --mandir=/usr/share/man \
        --enable-ipv6

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  # This MUST run after strip, which strips capabilities too!
  - runs: setcap cap_net_raw=+ep "${{targets.destdir}}"/usr/sbin/fping

subpackages:
  - name: "fping-doc"
    description: "fping manpages"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 834
