package:
  name: freerdp
  version: 2.11.6
  epoch: 0
  description: FreeRDP client
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - alsa-lib-dev
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      # - bsd-compat-headers
      - cmake
      - cups-dev
      - gsm-dev
      - gst-plugins-base-dev
      - libjpeg-turbo-dev
      - libusb-dev
      - libx11-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      # - libxkbfile-dev
      - libxkb-dev
      - libxkbcommon-dev
      - libxrender-dev
      - libxv-dev
      - linux-headers
      - openssl-dev>3
      - samurai

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/FreeRDP/FreeRDP/archive/${{package.version}}.tar.gz
      expected-sha512: 84b1828fcd238c2d3fa907c868271652668c8cc4719146e2e84ee3cb9a50854155ca66f69e92795ccd5ace040f15ed45812c63e16330c24f3be8c1ebae447d5a

  - runs: |
      CFLAGS="$CFLAGS -fPIC" \
      CXXFLAGS="$CXXFLAGS -fPIC" \
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DWITH_ALSA=ON \
        -DWITH_CUPS=ON \
        -DWITH_CHANNELS=ON \
        -DBUILTIN_CHANNELS=OFF \
        -DWITH_DIRECTFB=OFF \
        -DWITH_FFMPEG=OFF \
        -DWITH_GSM=ON \
        -DWITH_GSTREAMER_1_0=ON \
        -DWITH_IPP=OFF \
        -DWITH_JPEG=ON \
        -DWITH_OPENSSL=ON \
        -DWITH_PCSC=OFF \
        -DWITH_PULSE=OFF \
        -DWITH_WAYLAND=ON \
        -DWITH_SERVER=ON \
        -DWITH_X11=ON \
        -DWITH_XCURSOR=ON \
        -DWITH_XEXT=ON \
        -DWITH_XKBFILE=ON \
        -DWITH_XI=ON \
        -DWITH_XINERAMA=ON \
        -DWITH_XRENDER=ON \
        -DWITH_XV=ON \
        -DWITH_ZLIB=ON \
        -DWITH_NEON=OFF
       cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: freerdp-doc
    description: freerdp man pages
    pipeline:
      - uses: split/manpages

  - name: freerdp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - freerdp
    description: freerdp dev

  - name: freerdp-libs
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/* ${{targets.subpkgdir}}/usr/lib
    description: freerdp library

update:
  enabled: true
  github:
    identifier: FreeRDP/FreeRDP
    tag-filter-prefix: 2.
