package:
  name: gatekeeper-3.15
  version: 3.15.1
  epoch: 1
  description: Gatekeeper - Policy Controller for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - gatekeeper=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/open-policy-agent/gatekeeper
      tag: v${{package.version}}
      expected-commit: 3350319f76d3e2d78df0b972c63258cba7c7915f

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9 golang.org/x/net@v0.23.0

  - runs: |
      FRAMEWORKS_VERSION=$(go list -f '{{ .Version }}' -m github.com/open-policy-agent/frameworks/constraint)
      OPA_VERSION=$(go list -f '{{ .Version }}' -m github.com/open-policy-agent/opa)
      CGO_ENABLED=0 GO111MODULE=on go build -mod vendor -a -ldflags "-w -X github.com/open-policy-agent/gatekeeper/pkg/version.Version=v${{package.version}} -X main.frameworksVersion=${FRAMEWORKS_VERSION} -X main.opaVersion=${OPA_VERSION}" -o manager
      make gator
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./manager ${{targets.destdir}}/usr/bin/manager

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager
    dependencies:
      provides:
        - gatekeeper-compat=${{package.full-version}}

  - name: ${{package.name}}-gator
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv bin/gator ${{targets.subpkgdir}}/usr/bin/gator
    dependencies:
      provides:
        - gatekeeper-gator=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: open-policy-agent/gatekeeper
    strip-prefix: v
    use-tag: true
    tag-filter: v3.15.
