# source is gitlab so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: glab
  version: 1.39.0
  epoch: 0
  description: A GitLab CLI tool bringing GitLab to your command line
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/cli
      tag: v${{package.version}}
      expected-commit: 0a1bdd618fe1b70d2a215d88a68567a4e566bf5f

  - uses: go/build
    with:
      packages: ./cmd/glab
      output: glab
      ldflags: -s -w -X main.version=v${{package.version}}

update:
  enabled: true
  release-monitor:
    identifier: 127208
