package:
  name: gptscript
  version: 0.5.0
  epoch: 1
  description: Develop LLM Apps in Natural Language
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gptscript-ai/gptscript
      tag: v${{package.version}}
      expected-commit: 5a8a685cf3d6a132b673c766446f1743e87e3b52

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: .
      output: gptscript
      ldflags: -s -w  -X main.version=v${{ package.version }} -X main.revision=$(git rev-parse --short HEAD)

  - uses: strip

update:
  enabled: true
  github:
    identifier: gptscript-ai/gptscript
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        gptscript --version
