package:
  name: grype
  version: 0.77.0
  epoch: 1
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: b7ffbeee53105478e699290aeac238a0ead28962

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.0.2

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  pipeline:
    - runs: |
        grype --version
