package:
  name: harbor-scanner-trivy
  version: 0.31.0
  epoch: 2
  description: Use Trivy as a plug-in vulnerability scanner in the Harbor registry
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4c8fb7ad6ba4a20b67da89022bab4fbbe9cb6592
      repository: https://github.com/aquasecurity/harbor-scanner-trivy
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.0.2 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: ./cmd/scanner-trivy
      output: scanner-trivy

  - uses: strip

test:
  pipeline:
    - runs: |
        # No version or help info
        scanner-trivy & sleep 3; kill $!

update:
  enabled: true
  github:
    identifier: aquasecurity/harbor-scanner-trivy
    strip-prefix: v
