package:
  name: hcloud
  version: 1.43.1
  epoch: 0
  description: A command-line interface for Hetzner Cloud
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hetznercloud/cli
      tag: v${{package.version}}
      expected-commit: 22e3863f3d0c499d4b4573953b9a56cbadd0ec60

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/hcloud/main.go
      repository: https://github.com/hetnzercloud/cli
      ldflags: |
        -s -w
        -X main.version=internal/version.version=${{package.version}}
      output: hcloud

  - uses: strip

update:
  enabled: true
  github:
    identifier: hetznercloud/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        hcloud version
