package:
  name: hugo
  version: 0.125.4
  epoch: 1
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: cc3574ef4f41fccbe88d9443ed066eb10867ada2

  - uses: go/bump
    with:
      deps: github.com/gohugoio/hugo@v0.79.1

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
