package:
  name: hugo
  version: 0.125.1
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: 68c5ad638c2072969e47262926b912e80fd71a77

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
