package:
  name: kaniko
  version: 1.21.1
  epoch: 1
  description: Build Container Images In Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleContainerTools/kaniko
      tag: v${{package.version}}
      expected-commit: 6f57367e51dec5f1bb46ad8ec9a5801875d89b23

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.1.12 google.golang.org/protobuf@v1.33.0
      tidy: false

  - runs: |
      go mod tidy
      go mod vendor
      mkdir -p "${{targets.destdir}}"/usr/bin
      make out/executor
      install -m755 -D out/executor "${{targets.destdir}}"/usr/bin/executor

  - uses: strip

subpackages:
  - name: kaniko-warmer
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          make out/warmer
          install -m755 -D out/warmer "${{targets.subpkgdir}}"/usr/bin/warmer
      - uses: strip

  - name: kaniko-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /kaniko/
          mkdir -p ${{targets.subpkgdir}}/kaniko/
          ln -sf /usr/bin/executor ${{targets.subpkgdir}}/kaniko/
    dependencies:
      runtime:
        - kaniko

  - name: kaniko-warmer-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /kaniko/
          mkdir -p ${{targets.subpkgdir}}/kaniko/
          ln -sf /usr/bin/warmer ${{targets.subpkgdir}}/kaniko/
    dependencies:
      runtime:
        - kaniko-warmer

update:
  enabled: true
  github:
    identifier: GoogleContainerTools/kaniko
    strip-prefix: v
    use-tag: true
    tag-filter: v
