package:
  name: karpenter
  version: 0.36.0
  epoch: 1
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter
      tag: v${{package.version}}
      expected-commit: 6b868db24881714390f5b348130aadcd9fd9f8d9

  - uses: go/bump
    with:
      deps: k8s.io/apimachinery@v1.16.13

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/karpenter
    strip-prefix: v
