package:
  name: kubecolor
  version: 0.3.1
  epoch: 0
  description: Colorize your kubectl output
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - kubectl

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubecolor/kubecolor
      tag: v${{package.version}}
      expected-commit: ddf2f7588a64f973e87d62fdd00923e17f341485

  - uses: go/build
    with:
      packages: .
      repository: https://github.com/kubecolor/kubecolor
      ldflags: |
        -s -w
        -X main.version=${{package.version}}
      output: kubecolor

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubecolor/kubecolor
    strip-prefix: v

test:
  pipeline:
    - runs: |
        kubecolor version --client=true
