package:
  name: kube-logging-operator
  version: 4.6.0
  epoch: 2
  description: Logging operator for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kube-logging/logging-operator
      tag: ${{package.version}}
      expected-commit: 421fefebc813cb78d0ce26edd767ada97923519b

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - runs: |
      CGO_ENABLED=0 GO111MODULE=on go build -o bin/manager main.go
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/manager ${{targets.destdir}}/usr/bin/manager

  - uses: strip

subpackages:
  - name: "kube-logging-operator-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the logging-operator binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager
      - uses: strip

update:
  enabled: true
  github:
    identifier: kube-logging/logging-operator
