package:
  name: linux-headers
  version: 6.6.11
  epoch: 1
  description: "the Linux kernel headers (cross compilation)"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - scanelf
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/kernel/v6.x/linux-${{package.version}}.tar.gz
      expected-sha256: 188e61502d3030005790392ae2ca421619ae55c02316aa07f6e8b3a49555fd50

  - runs: |
      make mrproper

  - runs: |
      make headers
      find usr/include -name '.*' -delete
      rm usr/include/Makefile

      # Copy to cross-sysroot
      mkdir -p ${{targets.destdir}}/usr/include
      cp -rv usr/include/* ${{targets.destdir}}/usr/include/

update:
  enabled: true
  manual: true # be careful upgrading this package
  # the release monitor tracks only 6.6 LTS
  release-monitor:
    identifier: 370853
