package:
  name: mimalloc
  version: 1.8.4
  epoch: 0
  description: "A compact general purpose allocator with excellent performance"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/microsoft/mimalloc/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: b7a272de210a6fd7faa6c206eced79f6ffdf8655fe4fb755d36b66c66d7962f7

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

subpackages:
  - name: "mimalloc-dev"
    description: "headers for mimalloc"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mimalloc

update:
  enabled: true
  github:
    identifier: microsoft/mimalloc
    strip-prefix: v
    tag-filter: v1.
    use-tag: true
