package:
  name: minio
  version: 0.20240418.190919
  epoch: 0
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - perl

var-transforms:
  - from: ${{package.version}}
    match: ^0\.(\d{4})(\d{2})(\d{2})\.(\d{2})(\d{2})(\d{2})$
    replace: RELEASE.${1}-${2}-${3}T${4}-${5}-${6}Z
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/minio
      tag: ${{vars.mangled-package-version}}
      expected-commit: 98f7821eb3f60a6ece3125348a121a1238d02159

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv minio ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  version-transform:
    - match: ^RELEASE\.(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})Z$
      replace: 0.${1}${2}${3}.${4}${5}${6}
  github:
    identifier: minio/minio
    use-tag: true
