package:
  name: newrelic-nri-kube-events
  version: 2.9.5
  epoch: 0
  description: New Relic integration that forwards Kubernetes events to New Relic
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kube-events
      tag: v${{package.version}}
      expected-commit: 56cfaed2b7f3ee133ccc67e18c441ef44ecb5f91

  - uses: go/build
    with:
      packages: ./cmd/nri-kube-events
      ldflags: -s -w -X main.integrationVersion=v${{ package.version }}
      output: nri-kube-events

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-kube-events
    strip-prefix: v
    tag-filter: v
