package:
  name: nri-nagios
  version: 2.9.4
  epoch: 0
  description: New Relic Infrastructure Nagios Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-nagios
      expected-commit: 8df70baf875fdf59dc898eb217b5b2af7eee2a11
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-nagios
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/nagios-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/nagios-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-nagios
    strip-prefix: v
