package:
  name: nri-haproxy
  version: 3.0.1
  epoch: 0
  description: New Relic Infrastructure HAproxy Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-haproxy
      expected-commit: c323136e553d1e4162f0f8caef2046fda85bd7d7
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-haproxy
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/haproxy-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/haproxy-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-haproxy
    strip-prefix: v
