package:
  name: opentelemetry-collector
  version: 0.99.0
  epoch: 1
  description: OpenTelemetry Collector
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-collector
      tag: v${{package.version}}
      expected-commit: fb9d80d3c44c9007f2064baecc59687588d48499

  - runs: |
      set -x
      # Open-telementry builder documentation recommends using cmd/otelcorecol/builder-config.yaml
      # to build a default collector configuration:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder#running
      cp cmd/otelcorecol/builder-config.yaml .

      # Specify the output path
      sed -i '2i\ \ output_path: ./otel-col' ./builder-config.yaml

      # Replace some of the default values that refer to it as a testing or dev build.
      sed -i -E 's/description: .+/description: OpenTelemetry Collector/' ./builder-config.yaml
      sed -i -E 's/version: .+/version: ${{package.version}}/' ./builder-config.yaml

      # Change relative paths in replaces block from two levels to one level above root
      sed -i -E 's/\.\.\/\.\.\//\.\.\//' ./builder-config.yaml

  - uses: go/build
    with:
      packages: .
      modroot: ./cmd/builder
      output: ocb

  - runs: |
      set -x
      mkdir otel-col
      ${{targets.destdir}}/usr/bin/ocb --config=builder-config.yaml

  - runs: |
      install -Dm755 ./otel-col/otelcorecol "${{targets.destdir}}"/usr/bin/otelcorecol
      rm -f ${{targets.destdir}}/usr/bin/ocb

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compatability package to place binary in the location expected by upstream helm chart
    pipeline:
      - runs: |
          # The helm chart expects the binary to be /otelcol instead of /usr/bin/otelcorecol
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/otelcorecol ${{targets.subpkgdir}}/otelcol

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-collector
    strip-prefix: v
    use-tag: true
    tag-filter: v
