package:
  name: pnpm
  version: 9.0.2
  epoch: 0
  description: "Fast, disk space efficient package manager"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - ca-certificates-bundle
      - curl
      - gcc-12
      - git
      - make
      - node-gyp
      - nodejs-18
      - npm
      - pnpm
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pnpm/pnpm
      tag: v${{package.version}}
      expected-commit: d87d36e82e90ff95ecc4ec53c9e50100a3115d81

  - runs: |
      # upstream is using an alpha releaae if pnpm 9
      sed -i 's/"pnpm": ">=9"/"pnpm": ">=8.6.10"/g' package.json
      /usr/bin/pnpm install
      /usr/bin/pnpm run compile
      mkdir -p "${{targets.destdir}}"/usr/lib/node_modules/pnpm
      mkdir -p "${{targets.destdir}}"/usr/bin/
      cd pnpm

      ln -sf /usr/lib/node_modules/pnpm/bin/pnpm.cjs  "${{targets.destdir}}"/usr/bin/pnpm
      ln -sf /usr/lib/node_modules/pnpm/bin/pnpx.cjs  "${{targets.destdir}}"/usr/bin/pnpx
      mv bin  "${{targets.destdir}}"/usr/lib/node_modules/pnpm
      mv dist "${{targets.destdir}}"/usr/lib/node_modules/pnpm

update:
  enabled: true
  github:
    identifier: pnpm/pnpm
    strip-prefix: v
    tag-filter: v
