package:
  name: pulumi-language-dotnet
  version: 3.62.0
  epoch: 1
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: eddc031822bfa0d657c139d69a62d4646f42ed57
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/go-git/go-git/v5@v5.11.0 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0
      modroot: pulumi-language-dotnet
      replaces: github.com/cloudflare/circl=github.com/cloudflare/circl@v1.3.7

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/pulumi/pulumi-language-dotnet/pkg/version.Version=v${{package.version}}
      modroot: pulumi-language-dotnet
      output: pulumi-language-dotnet
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v
