package:
  name: pulumi-language-dotnet
  version: 3.61.0
  epoch: 0
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f40c85e9bb614a48a574ffe22ee58cb225ab7d8d
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/go-git/go-git/v5@v5.11.0 google.golang.org/protobuf@v1.33.0
      modroot: pulumi-language-dotnet
      replaces: github.com/cloudflare/circl=github.com/cloudflare/circl@v1.3.7

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/pulumi/pulumi-language-dotnet/pkg/version.Version=v${{package.version}}
      modroot: pulumi-language-dotnet
      output: pulumi-language-dotnet
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v
