package:
  name: py3-sphinx
  version: 7.3.6
  epoch: 0
  description: "Python Documentation Generator"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sphinx-doc/sphinx/archive/v${{package.version}}.tar.gz
      expected-sha512: 3c5485949567d92c76b8c4db1b8a8f8c5830082d813cbfeda1130bb36b01ec7b6800b0acd5b8c7b26853a01094c1c072efdc80a9860740340ab266cc27bc1238

  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinx-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinx
    strip-prefix: v
