package:
  name: py3-python-lsp-jsonrpc
  version: 1.1.2
  epoch: 2
  description: "JSON RPC 2.0 server library"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-ujson
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-setuptools-scm
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-lsp/python-lsp-jsonrpc
      tag: v${{package.version}}
      expected-commit: 786d8dd8f830dbd83a17962c0167183a6609e72f

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/python_lsp_jsonrpc-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-lsp/python-lsp-jsonrpc
    strip-prefix: v
