package:
  name: py3-meson-python
  version: 0.16.0
  epoch: 0
  description: Meson Python build backend (PEP 517)
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - meson
      - py3-colorama
      - py3-packaging
      - py3-pyproject-metadata
      - py3-setuptools
      - py3-tomli
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson
      - py3-colorama
      - py3-gpep517
      - py3-packaging
      - py3-pyproject-metadata
      - py3-setuptools
      - py3-tomli
      - py3-wheel
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mesonbuild/meson-python
      tag: ${{package.version}}
      expected-commit: 4f50bf27ef5282f8147c1df073d27859bda5e890

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: mesonbuild/meson-python
    use-tag: true
