package:
  name: py3-hatchling
  version: 1.24.2
  epoch: 0
  description: "Modern, extensible Python build backend"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-pathspec
      - py3-pluggy
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/h/hatchling/hatchling-${{package.version}}-py3-none-any.whl
      expected-sha512: fe6ef32aea0dd60ec36c34954b4345b55f031a694d24c4c18e1d77d7115b18bedf3d74f71a849d3a5c540d6361cd97c93ae20bbdbf306b7d249ab80999e7b33a
      extract: false
      delete: false

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" ./hatchling-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 185085
