package:
  name: py3-pygments
  version: 2.17.2
  epoch: 1
  description: Syntax highlighting package written in Python
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pygments/pygments.git
      tag: ${{package.version}}
      expected-commit: ee30ce132ae252bd72f3a74c86d9314a2214d0b4

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - runs: |
      sed -i '1s|^#!/usr/bin/python$|#!/usr/bin/python3|' ${{targets.destdir}}/usr/bin/pygmentize

subpackages:
  - name: py3-pygments-doc
    pipeline:
      - runs: |
          destdir=${{targets.subpkgdir}}/usr/share/doc/py3-pygments

          cd "$builddir"

          install -m 644 -D doc/pygmentize.1 \
            ${{targets.subpkgdir}}/usr/share/man/man1/pygmentize.1

          mkdir -p "$destdir"
          cp AUTHORS CHANGES LICENSE "$destdir"/

          # Note: The documentation in the doc directory needs to be generated
          # by py-sphinx
          cp -R ./doc/docs/* "$destdir"/
      - uses: split/manpages
    description: py3-pygments manpages

update:
  enabled: true
  github:
    identifier: pygments/pygments
