package:
  name: py3-botocore
  version: 1.34.86
  epoch: 0
  description: The low-level, core functionality of Boto3
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-dateutil
      - py3-docutils
      - py3-jmespath
      - py3-urllib3
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
      expected-sha256: 2fd62b63d8788e15629bfc95be1bd2d99c0da6c1d45ef1f40c0a0101e412f6b5

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 29738

test:
  pipeline:
    - runs: |
        LIBRARY="botocore"
        IMPORT_STATEMENT="import botocore"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
