package:
  name: py3-sphinx
  version: 7.3.7
  epoch: 0
  description: "Python Documentation Generator"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sphinx-doc/sphinx/archive/v${{package.version}}.tar.gz
      expected-sha512: 540553ecddc55b3e673c79bc776a899d2c660f1e93ef819711be52174accf5b70465883a46bed81d163534e56718caf0765b4bae153e9307a3792387d8228df5

  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinx-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinx
    strip-prefix: v
