package:
  name: py3-traitlets
  version: 5.14.3
  epoch: 0
  description: Traitlets Python configuration system
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - python3
      - rsync
      - wolfi-base
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ipython/traitlets
      expected-commit: 13de53c537a257402035139dd6862558eb19d362
      tag: v${{package.version}}

  - name: Install hatchling
    runs: |
      python3 -m pip install hatch

  - name: Copy project
    runs: |
      mkdir -p "${{targets.destdir}}/lib"
      rsync -a --exclude='melange-out/*' . "${{targets.destdir}}/lib/traitlets"

  - name: Build project
    runs: |
      cd "${{targets.destdir}}/lib/traitlets"
      hatch build
      python3 -m pip install dist/*.whl --target "${{targets.destdir}}/usr/lib/python3.12/site-packages/"

  - uses: strip

update:
  enabled: true
  github:
    identifier: ipython/traitlets
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - runs: |
        /usr/bin/python3 -c 'from traitlets import HasTraits'
