package:
  name: py3-hatchling
  version: 1.24.1
  epoch: 0
  description: "Modern, extensible Python build backend"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-pathspec
      - py3-pluggy
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/h/hatchling/hatchling-${{package.version}}-py3-none-any.whl
      expected-sha512: 9e423c719f2eba90d949efb1dbdad22ae71cad0e8490c5ee37fdf0a51bb63084f5bf288259c5ab97a4a19b1a36709a553f7e2fa2662c2daf243ce1fe751fcf8a
      extract: false
      delete: false

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" ./hatchling-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 185085
