package:
  name: py3-click-option-group
  version: 0.5.6
  epoch: 2
  description: "Option groups missing in Click."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-click
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/click-contrib/click-option-group
      tag: v${{package.version}}
      expected-commit: 515950e26672c347922dbe3c7b2cc8ac0bd33856

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/click_option_group-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: click-contrib/click-option-group
    strip-prefix: v
