package:
  name: ruby3.2-protocol-http
  version: 0.26.4
  epoch: 0
  description: Provides abstractions to handle HTTP protocols.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: protocol-http

pipeline:
  - uses: fetch
    with:
      expected-sha256: 055b581721a6e8aab92bdf995591cb9c6e5b4b10291a5598b7e88d8351832236
      uri: https://github.com/socketry/protocol-http/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http
    strip-prefix: v
    use-tag: true
