package:
  name: ruby3.2-async-io
  version: 1.43.2
  epoch: 0
  description: Provides support for asynchonous TCP, UDP, UNIX and SSL sockets.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-async

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async-io

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7fd67a6df2000be71f0eb22466f4d770a2ccd1d6e63c6b7befe8b7fb0e899aa5
      uri: https://github.com/socketry/async-io/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async-io
    strip-prefix: v
    use-tag: true
