package:
  name: ruby3.2-async-http
  version: 0.65.0
  epoch: 0
  description: A HTTP client and server library.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-async
      - ruby3.2-async-io
      - ruby3.2-async-pool
      - ruby3.2-protocol-http
      - ruby3.2-protocol-http1
      - ruby3.2-protocol-http2
      - ruby3.2-traces

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async-http

pipeline:
  - uses: fetch
    with:
      expected-sha256: dae7d1507ee36b9ad59ed74f72f3625ff059c39e603befd4a580736783b1bcd4
      uri: https://github.com/socketry/async-http/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async-http
    strip-prefix: v
    use-tag: true
