package:
  name: ruby3.2-protocol-http2
  version: 0.17.0
  epoch: 0
  description: A low level implementation of the HTTP/2 protocol.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-protocol-hpack
      - ruby3.2-protocol-http

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: protocol-http2

pipeline:
  - uses: fetch
    with:
      expected-sha256: e893a1c3b08aee31dbd11b2cf42447cba8f418599112f9db1d478d4d20079cb1
      uri: https://github.com/socketry/protocol-http2/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http2
    strip-prefix: v
    use-tag: true
