package:
  name: ruby3.2-console
  version: 1.24.0
  epoch: 0
  description: Beautiful logging for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-fiber-local

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: console

pipeline:
  - uses: fetch
    with:
      expected-sha256: c856add94af3a04ba88ce7c12d5bcbb0639393aeb6c1a6a3b08613703a17c396
      uri: https://github.com/socketry/console/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/console
    strip-prefix: v
    use-tag: true
