package:
  name: ruby3.2-async-pool
  version: 0.6.1
  epoch: 0
  description: A singleplex and multiplex resource pool for implementing robust clients.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-async

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async-pool

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7c936f51a10b1ce34962a1e69495683207cfeed4b631ab6d0fcdec7c995e7e29
      uri: https://github.com/socketry/async-pool/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async-pool
    strip-prefix: v
    use-tag: true
