package:
  name: ruby-3.3
  version: 3.3.1 # You may have to remove bump-rdoc.patch at the next version
  epoch: 0
  description: "the Ruby programming language"
  copyright:
    - license: Ruby
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - oniguruma-dev
      - openssl-dev
      - readline-dev
      - rust
      - sqlite-dev
      - xz-dev
      - yaml-dev
      - zlib-dev

vars:
  prefix: /usr

pipeline:
  - uses: fetch
    with:
      uri: https://cache.ruby-lang.org/pub/ruby/3.3/ruby-${{package.version}}.tar.gz
      expected-sha256: 8dc2af2802cc700cd182d5430726388ccf885b3f0a14fcd6a0f21ff249c9aa99

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=${{vars.prefix}} \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --enable-yjit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |-
      # Ignore the patch version of ruby since ruby will install under the
      # version of the latest standard library. Should produce the string 3.3.*
      RUBYWILD="$(echo ${{package.version}} | cut -d. -f-2).*"

      RUBYDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/$RUBYWILD
      rm -rf ${RUBYDIR}/bundler
      rm ${RUBYDIR}/bundler.rb

      GEMDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/gems/$RUBYWILD
      rm -rf ${GEMDIR}/gems/bundler-*
      rm ${GEMDIR}/specifications/default/bundler-*.gemspec

      rm ${{targets.destdir}}/usr/bin/bundle \
         ${{targets.destdir}}/usr/bin/bundler

subpackages:
  - name: "ruby-3.3-doc"
    description: "ruby documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/ri "${{targets.subpkgdir}}"/usr/share/

  - name: "ruby-3.3-dev"
    description: "ruby development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  manual: true # be careful with auto updates
  release-monitor:
    identifier: 4223

test:
  pipeline:
    - runs: |
        ruby --version

        cat <<EOF >> /tmp/hello.rb
        puts("Hello Wolfi!")
        EOF

        ruby /tmp/hello.rb
