package:
  name: spegel
  version: 0.0.21
  epoch: 1
  description: Stateless cluster local OCI registry mirror.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/spegel-org/spegel
      tag: v${{package.version}}
      expected-commit: 024f04a5f8a736d88702f3c78c8a37750e36151b

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: ./
      ldflags: "-s -w -extldflags '-static'"
      output: spegel

  - uses: strip

update:
  enabled: true
  github:
    identifier: spegel-org/spegel
    strip-prefix: v

# This is a statically compiled go app, we don't need to get crazy here.
test:
  pipeline:
    - name: Verify spegel is present and runs
      runs: |
        spegel --help
