package:
  name: step-kms-plugin
  version: 0.11.1
  epoch: 0
  description: step plugin to manage keys and certificates on a cloud KMSs and HSMs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "1"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/step-kms-plugin
      tag: v${{package.version}}
      expected-commit: 3fd4570ed7da6f6b9aaf4e2e1908dc310a497411

  - uses: go/build
    with:
      packages: ./cmd
      output: step-kms-plugin
      ldflags: -w -X "main.Version=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: smallstep/step-kms-plugin
    strip-prefix: v
