package:
  name: suricata
  version: 7.0.5
  epoch: 0
  description: "Suricata is a network Intrusion Detection System, Intrusion Prevention System and Network Security Monitoring engine"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - libhtp
      - suricata-update

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - elfutils-dev
      - glibc-dev
      - icu
      - jansson-dev
      - libbpf-dev
      - libcap-ng-dev
      - libevent-dev
      - libhtp-dev
      - libnetfilter_queue-dev
      - libpcap-dev
      - libtool
      - m4
      - openssl-dev
      - pcre2-dev
      - pkgconf-dev
      - posix-libc-utils
      - python3
      - rust
      - wolfi-base
      - yaml-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/OISF/suricata/archive/refs/tags/suricata-${{package.version}}.tar.gz
      expected-sha256: a67d2a8b86d31706617dc4bfc6bb00540b8be5199e2b0cbacb9963c699719ea8

  - runs: |
      cargo install --force --root /usr/ cbindgen

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --enable-non-bundled-htp \
        --enable-nfqueue \
        --enable-gccprotect \
        --enable-enable_evelog \
        --enable-ebpf \
        --disable-suricata-update \
        --prefix=/usr/ \
        --sysconfdir=/etc/ \
        --localstatedir=/var/

  - uses: autoconf/make-install
    with:
      opts: |
        DESTDIR=${{targets.destdir}} install-full

  - runs: |
      install -d -m0750 ${{targets.destdir}}/etc/suricata
      install -d -m0750 ${{targets.destdir}}/var/lib/suricata
      install -d -m0750 ${{targets.destdir}}/var/log/suricata
      make -j1 DESTDIR=${{targets.destdir}} install-full

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 10925
