package:
  name: syft
  version: 1.0.1
  epoch: 1
  description: CLI tool and library for generating a Software Bill of Materials from container images and filesystems
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/syft
      tag: v${{package.version}}
      expected-commit: 1b121ac3f4d589060ddf1fac0bcd6871ea4731e3

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: syft
      packages: ./cmd/syft

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/syft
    strip-prefix: v

test:
  pipeline:
    - runs: |
        syft --version
