package:
  name: tekton-chains
  version: 0.20.0
  epoch: 4
  description: Supply Chain Security in Tekton Pipelines
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d5a565997f99a809426b53b3d5d40c487d4e2b30
      repository: https://github.com/tektoncd/chains
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7 github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      output: tekton-chains
      packages: ./cmd/controller

update:
  enabled: true
  github:
    identifier: tektoncd/chains
    strip-prefix: v
