package:
  name: timoni
  version: 0.21.0
  epoch: 0
  description: Timoni is a package manager for Kubernetes, powered by CUE and inspired by Helm.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stefanprodan/timoni
      tag: v${{package.version}}
      expected-commit: 28426b0e1539089403b26fba798b02ce123a577b

  - uses: go/build
    with:
      packages: ./cmd/timoni
      output: timoni
      ldflags: -s -w -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: stefanprodan/timoni
    strip-prefix: v
    use-tag: true
    tag-filter: v
