package:
  name: trurl
  version: "0.12"
  epoch: 0
  description: 'trurl is a command line tool for URL parsing and manipulation.'
  copyright:
    - license: curl

environment:
  contents:
    packages:
      - build-base
      - busybox
      - curl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/curl/trurl/archive/refs/tags/trurl-0.10.tar.gz
      expected-sha256: e54ee05a1a39f2547fbb39225f9cf5e2608eeaf07ad3f7dbff0a069d060d3c46

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "trurl-doc"
    description: "documentation for trurl"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/trurl
    strip-prefix: trurl-

test:
  pipeline:
    - runs: |
        trurl --version
        trurl --url https://curl.se/we/are.html --get '{port}'
