package:
  name: util-macros
  version: 1.20.1
  epoch: 0
  description: X.Org Autotools macros
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: b373f72887b1394ce2193180a60cb0d1fb8b17bc96ddd770cfd7a808cb489a15
      uri: https://www.x.org/releases/individual/util/util-macros-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  release-monitor:
    identifier: 5252
