package:
  name: valkey
  version: 7.2.5
  epoch: 0
  description: Advanced key-value store
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provides:
      - redis=${{package.full-version}}
    runtime:
      - posix-libc-utils # `getent` is required on startup in ha mode for ip introspection cluster formation

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/valkey-io/valkey
      tag: ${{package.version}}
      expected-commit: 26388270f197bce84817eea0a73d687d58442654

  - uses: patch
    with:
      patches: 0000-Disable-protected-mode.patch

  - runs: |
      export CFLAGS="$CFLAGS -DUSE_MALLOC_USABLE_SIZE"
        make USE_JEMALLOC=no \
        MALLOC=libc \
        BUILD_TLS=yes \
        all -j$(nproc)
      make install PREFIX=/usr INSTALL_BIN="${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: valkey-cli
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/valkey-cli "${{targets.subpkgdir}}"/usr/bin/valkey-cli
    description: valkey-cli is the command line interface utility to talk with Valkey.

  - name: valkey-benchmark
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/valkey-benchmark "${{targets.subpkgdir}}"/usr/bin/valkey-benchmark
    description: valkey-benchmark utility that simulates running commands done by N clients while at the same time sending M total queries.

update:
  enabled: true
  github:
    identifier: valkey-io/valkey

test:
  environment:
    contents:
      packages:
        - valkey-cli
  pipeline:
    - runs: |
        cat <<EOF >> /tmp/valkey.conf
        dbfilename dump.rdb
        pidfile /tmp/valkey_6379.pid
        dir /tmp/
        EOF

        valkey-server /tmp/valkey.conf &
        sleep 2 # wait for valkey to start
        valkey-cli SET bike:1 "Process 134" || exit 1
        valkey-cli GET bike:1 | grep 'Process 134' || exit 1
        valkey-cli exists bike:1 | grep 1 || exit 1
        valkey-cli exists bike:2 | grep 0 || exit 1
