package:
  name: wasi-sdk
  version: "22"
  epoch: 0
  description: "WASI-enabled WebAssembly C/C++ toolchain"
  copyright:
    - license: Apache-2.0
  # This package ships its own version of clang configured to work with wasm, set no-provides to make sure it doesn't confuse the solver.
  # Anyone using it should ask for it explicitly
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-17
      - clang-17-dev
      - cmake
      - llvm17
      - perl
      - python3
      - rust
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/WebAssembly/wasi-sdk
      tag: wasi-sdk-${{package.version}}
      expected-commit: 99abb024209dc7a9a8d8f3eb6d03908a18bb0594
      recurse-submodules: true

  - name: Build
    runs: |
      # wasi-ld breaks with a few of the ones we set normally
      export LDFLAGS=$(echo $LDFLAGS | sed 's/,--as-needed//g')
      export LDFLAGS=$(echo $LDFLAGS | sed 's/,--sort-common//g')
      PREFIX=/usr make build

  - runs: |
      mkdir -p ${{targets.destdir}}
      mv build/install/* ${{targets.destdir}}/

  - uses: strip

subpackages:
  # This has to come before the split/dev step
  - name: wasi-sdk-libclang-rt-builtins
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/clang/lib/wasi
          # Copy instead of move because this also needs to be in the -dev package
          cp ${{targets.destdir}}/usr/lib/clang/18/lib/wasi/libclang_rt.builtins-wasm32.a ${{targets.subpkgdir}}/usr/lib/clang/lib/wasi/

  - name: wasi-sdk-sysroot
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/share/wasi-sysroot/ ${{targets.subpkgdir}}/usr/share/

  - name: wasi-sdk-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: WebAssembly/wasi-sdk
    strip-prefix: wasi-sdk-
    use-tag: true
