package:
  name: whois
  version: 5.5.22
  epoch: 0
  description: "Intelligent WHOIS client"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - gettext
      - perl
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rfc1036/whois
      tag: v${{package.version}}
      expected-commit: 481b0abe71fb53600cf2442d5824f847c1b5a607

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |
      rm -rf ${{targets.destdir}}/etc

subpackages:
  - name: man-whois
    pipeline:
      - uses: split/manpages
    description: whois manpages

update:
  enabled: true
  github:
    identifier: rfc1036/whois
    tag-filter: v
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - name: Verify mkpasswd installation
      runs: |
        mkpasswd --version || exit 1
    - name: Verify whois installation
      runs: |
        whois --version || exit 1
