package:
  name: wolfictl
  version: 0.15.19
  epoch: 1
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 1eda4038e7529de18d3c45c20ad3ec49a45ad50f
      destination: wolfictl

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 github.com/docker/docker@v26.0.2
      modroot: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
