package:
  name: wolfictl
  version: 0.16.0
  epoch: 0
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 7aec89f90813eaa9d0a67e2d5efbecf7cdfea6a0
      destination: wolfictl

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.0.2
      modroot: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
