package:
  name: wolfictl
  version: 0.16.2
  epoch: 1
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 0c92fc49ef9a9dd804f2bac5bd8bd890f6c7fe41
      destination: wolfictl

  - uses: go/bump
    with:
      deps: k8s.io/apimachinery@v1.16.13
      modroot: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
