package:
  name: yam
  version: 0.0.4
  epoch: 0
  description: A sweet little formatter for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/yam
      tag: v${{package.version}}
      expected-commit: 4a88be1ed11979a8204dbe9d1a4e00cba1512a77

  - uses: go/build
    with:
      packages: .
      output: yam

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/yam
    use-tag: true
    strip-prefix: v
