package:
  name: yazi
  version: 0.2.5
  epoch: 0
  description: Blazing fast terminal file manager written in Rust, based on async I/O.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - file

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sxyazi/yazi
      tag: v${{package.version}}
      expected-commit: c65a14c0e650c92cce52fe507b9f84a873cae44d

  - runs: |
      cargo build --release

      install -Dm755 ./target/release/yazi "${{targets.destdir}}"/usr/bin/yazi

  - uses: strip

update:
  enabled: true
  github:
    identifier: sxyazi/yazi
    strip-prefix: v

test:
  pipeline:
    - runs: |
        yazi --version
