package:
  name: ytt
  version: 0.49.0
  epoch: 0
  description: YAML templating tool that works on YAML structure instead of text
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: fetch
    with:
      expected-sha256: 59a45c67882b64ef61c64435a2c96e9fad004f4e19982916b8e001444079f54b
      uri: https://github.com/carvel-dev/ytt/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: go/build
    with:
      packages: ./cmd/ytt
      output: ytt
      ldflags: -w -X github.com/vmware-tanzu/carvel-ytt/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/ytt
    strip-prefix: v
