package:
  name: zarf
  version: 0.33.0
  epoch: 2
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 5a7314e2a0dce4466dffcb95b7d088048bdcec9d
      repository: https://github.com/defenseunicorns/zarf
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 k8s.io/apimachinery@v1.16.13 golang.org/x/net@v0.23.0
      replaces: github.com/prometheus/common=github.com/prometheus/common@v0.45.0 github.com/prometheus/client_golang=github.com/prometheus/client_golang@v1.18.0
      show-diff: true

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
