package:
  name: zookeeper-3.9
  version: 3.9.2.0
  epoch: 2
  description: Distributed, highly available, robust, fault-tolerant system for distributed coordination
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-17-default-jvm
      - xmlstarlet
    provides:
      - zookeeper=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: \.(\d+)$
    replace: "-$1"
    to: mangled-package-version
  - from: ${{package.version}}
    match: ^(\d+\.\d+\.\d+)\.\d+$
    replace: "$1"
    to: short-package-version

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/zookeeper
      tag: release-${{vars.mangled-package-version}}
      expected-commit: e454e8c7283100c7caec6dcae2bc82aaecb63023

  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      # patch netty version for CVE-2023-4586 CVE-2023-44487
      mvn install -DskipTests -Dnetty.version=4.1.100.Final
      tar -xf zookeeper-assembly/target/apache-zookeeper-${{vars.short-package-version}}-bin.tar.gz

      mkdir -p ${{targets.destdir}}/usr/share/java/zookeeper
      mkdir -p ${{targets.destdir}}/usr/share/java/zookeeper/bin
      mkdir -p ${{targets.destdir}}/usr/share/java/zookeeper/lib
      mkdir -p ${{targets.destdir}}/usr/share/java/zookeeper/conf
      mkdir -p ${{targets.destdir}}/usr/share/java/zookeeper/logs

      # Clean up windows files
      rm -rf apache-zookeeper-${{vars.short-package-version}}-bin/bin/*.cmd
      mv apache-zookeeper-${{vars.short-package-version}}-bin/lib/* ${{targets.destdir}}/usr/share/java/zookeeper/lib
      mv apache-zookeeper-${{vars.short-package-version}}-bin/bin/* ${{targets.destdir}}/usr/share/java/zookeeper/bin
      mv apache-zookeeper-${{vars.short-package-version}}-bin/conf/* ${{targets.destdir}}/usr/share/java/zookeeper/conf

subpackages:
  - name: zookeeper-bitnami-3.9-compat
    description: "compat package with bitnami/zookeper image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: zookeeper
          version-path: 3.9/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/zookeeper/
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/zookeeper/bin
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/zookeeper/conf
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/zookeeper/conf.default
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/zookeeper/logs
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/scripts/zookeeper/

          cp -r ${{targets.destdir}}/usr/share/java/zookeeper/bin/* ${{targets.subpkgdir}}/opt/bitnami/zookeeper/bin
          ln -s /usr/share/java/zookeeper/lib ${{targets.subpkgdir}}/opt/bitnami/zookeeper/lib
          cp -r conf/* ${{targets.subpkgdir}}/opt/bitnami/zookeeper/conf/
          cp -r conf/* ${{targets.subpkgdir}}/opt/bitnami/zookeeper/conf.default

          # create symlinks for both /entrypoint.sh and /run.sh to make it compatible with bitnami/zookeeper helm chart
          ln -sf /opt/bitnami/scripts/zookeeper/entrypoint.sh "${{targets.subpkgdir}}"/entrypoint.sh
          ln -sf /opt/bitnami/scripts/zookeeper/run.sh "${{targets.subpkgdir}}"/run.sh
    dependencies:
      provides:
        - zookeeper-bitnami-compat=${{package.full-version}}

update:
  enabled: true
  version-separator: "-"
  github:
    tag-filter: release-3.9
    identifier: apache/zookeeper
    strip-prefix: release-
    use-tag: true
