package:
  name: zot
  version: 2.0.2
  epoch: 1
  description: A production-ready vendor-neutral OCI-native container image registry (purely based on OCI Distribution Specification)
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - go-1.21

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ce7a9466c6a768b5ae57a13068ae6f7a01e3038e
      repository: https://github.com/project-zot/zot
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v25.0.5

  - runs: |
      GOARCH=$(go env GOARCH)

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy binary
      install -m755 -D ./bin/zot-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zot

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy cli
      install -m755 -D ./bin/zli-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zli

  - uses: strip

update:
  enabled: true
  github:
    identifier: project-zot/zot
    strip-prefix: v
