package:
  name: zot
  version: 2.0.3
  epoch: 4
  description: A production-ready vendor-neutral OCI-native container image registry (purely based on OCI Distribution Specification)
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 819994cca1f3be3827c2dbf9756687f5be279401
      repository: https://github.com/project-zot/zot
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 golang.org/x/net@v0.23.0

  - runs: |
      GOARCH=$(go env GOARCH)

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy binary
      install -m755 -D ./bin/zot-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zot

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy cli
      install -m755 -D ./bin/zli-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zli

  - uses: strip

update:
  enabled: true
  github:
    identifier: project-zot/zot
    strip-prefix: v
