issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: lifecycle-upstream-github@prod-images-c6e5.iam.gserviceaccount.com
subject: "100889997859037637297"

permissions:
  contents: read
  metadata: read
